spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
    discovery:
      enabled: true
  application:
    name: gateway-service
server:
  port: 8080